### PR TITLE
add elastic derformation - bsplines itkbased

### PR DESCRIPTION
**Pull request by elitap**

### CODE REVIEW

**Comment by tvercaut** [comment]
Many thanks @elitap for your contribution. Our main development hub is on our GitLab server: https://github.com/NifTK/NiftyNet/blob/dev/CONTRIBUTING.md 

We are currently working on ironing out our integration workflow between GitHub and GitLab: https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/issues/174

As such, it might take a bit of time before we go through your PR.

**Comment by dzhoshkun** [comment]
@elitap Thank you very much for your contributions. We've now worked out a workflow for merging GitHub PRs to our main development hub (CMICLab). I've noticed that you've been adding more commits to this PR. Please let us know when it's ready for merging, so we can review and merge it.

**Comment by elitap** [comment]
Thank you for considering to merge. However, as for now, the elastic deformation I added requires SimpleITK. Still, I added all the sanity checkes to ignore the option if sitk is not available. I run your test script run_test.sh and merged everything with the current dev branch. So the most recent commit d25f90e01587751875712856e71391cedd0eda43 should be fine, if you wish to merge.

**Comment by wyli** [comment]
Thanks, commit https://github.com/NifTK/NiftyNet/commit/eb6bad7b1b50e517b3bd7c8b7bec35888f4e68c2 is now merged.

**Pull request closed without merging**
